// Package sqlcgen is the sqlc-generated metadata query package. Do not edit.
// input: internal/meta/sql/*.sql and the migrations schema
// output: typed query methods for leases, task runs, and worker heartbeats
// pos: generated query layer under internal/meta; refresh with make sqlc-generate
// note: if this file changes, update this header and module README.md.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"context"
	"database/sql"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}
