// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: lease.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const acquireTaskLease = `-- name: AcquireTaskLease :exec
INSERT INTO task_leases (task_id, owner_worker_id, epoch, lease_expire_at, renewed_at)
VALUES (
  ?,
  ?,
  1,
  DATE_ADD(NOW(6), INTERVAL ? MICROSECOND),
  NOW(6)
)
ON DUPLICATE KEY UPDATE
  owner_worker_id = IF(lease_expire_at <= NOW(6), ?, owner_worker_id),
  epoch = IF(lease_expire_at <= NOW(6), epoch + 1, epoch),
  lease_expire_at = IF(
    lease_expire_at <= NOW(6),
    DATE_ADD(NOW(6), INTERVAL ? MICROSECOND),
    lease_expire_at
  ),
  renewed_at = IF(lease_expire_at <= NOW(6), NOW(6), renewed_at)
`

type AcquireTaskLeaseParams struct {
	TaskID    string
	WorkerID  string
	TtlMicros interface{}
}

func (q *Queries) AcquireTaskLease(ctx context.Context, arg AcquireTaskLeaseParams) error {
	_, err := q.db.ExecContext(ctx, acquireTaskLease,
		arg.TaskID,
		arg.WorkerID,
		arg.TtlMicros,
		arg.WorkerID,
		arg.TtlMicros,
	)
	return err
}

const getCurrentDBTime = `-- name: GetCurrentDBTime :one
SELECT NOW(6)
`

func (q *Queries) GetCurrentDBTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getCurrentDBTime)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const getTaskLease = `-- name: GetTaskLease :one
SELECT task_id, owner_worker_id, epoch, lease_expire_at, renewed_at
FROM task_leases
WHERE task_id = ?
`

func (q *Queries) GetTaskLease(ctx context.Context, taskID string) (TaskLease, error) {
	row := q.db.QueryRowContext(ctx, getTaskLease, taskID)
	var i TaskLease
	err := row.Scan(
		&i.TaskID,
		&i.OwnerWorkerID,
		&i.Epoch,
		&i.LeaseExpireAt,
		&i.RenewedAt,
	)
	return i, err
}

const releaseTaskLease = `-- name: ReleaseTaskLease :execresult
UPDATE task_leases
SET owner_worker_id = '', lease_expire_at = NOW(6), renewed_at = NOW(6)
WHERE task_id = ?
  AND owner_worker_id = ?
  AND epoch = ?
`

type ReleaseTaskLeaseParams struct {
	TaskID   string
	WorkerID string
	Epoch    int64
}

func (q *Queries) ReleaseTaskLease(ctx context.Context, arg ReleaseTaskLeaseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, releaseTaskLease, arg.TaskID, arg.WorkerID, arg.Epoch)
}

const renewTaskLease = `-- name: RenewTaskLease :execresult
UPDATE task_leases
SET lease_expire_at = DATE_ADD(NOW(6), INTERVAL ? MICROSECOND), renewed_at = NOW(6)
WHERE task_id = ?
  AND owner_worker_id = ?
  AND epoch = ?
`

type RenewTaskLeaseParams struct {
	TtlMicros interface{}
	TaskID    string
	WorkerID  string
	Epoch     int64
}

func (q *Queries) RenewTaskLease(ctx context.Context, arg RenewTaskLeaseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, renewTaskLease,
		arg.TtlMicros,
		arg.TaskID,
		arg.WorkerID,
		arg.Epoch,
	)
}
