// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"database/sql"
	"encoding/json"
	"time"
)

type BackupCheckpoint struct {
	TaskID    string
	FileName  string
	Pos       uint64
	GtidSet   sql.NullString
	UpdatedAt time.Time
}

type BackupTask struct {
	ID            string
	Name          string
	ClusterKey    string
	State         string
	LastError     sql.NullString
	OwnerWorkerID sql.NullString
	Epoch         int64
	RunID         sql.NullString
	SourceJson    json.RawMessage
	StartJson     json.RawMessage
	StorageJson   json.RawMessage
	UpdatedAt     time.Time
}

type BinlogFile struct {
	ID          uint64
	TaskID      string
	FileName    string
	SourceFile  sql.NullString
	FilePath    string
	Epoch       int64
	State       string
	Checksum    sql.NullString
	SizeBytes   int64
	StartPos    uint64
	EndPos      uint64
	CreatedAt   time.Time
	SealedAt    time.Time
	ObjectKey   sql.NullString
	UploadState string
	UploadError sql.NullString
	UploadedAt  sql.NullTime
}

type TaskEvent struct {
	ID        uint64
	TaskID    string
	EventType string
	Message   sql.NullString
	Detail    sql.NullString
	EventTime time.Time
	EventSeq  int64
}

type TaskLease struct {
	TaskID        string
	OwnerWorkerID string
	Epoch         int64
	LeaseExpireAt time.Time
	RenewedAt     time.Time
}

type TaskRun struct {
	RunID     string
	TaskID    string
	WorkerID  string
	Epoch     int64
	StartedAt time.Time
	EndedAt   sql.NullTime
	EndReason sql.NullString
}

type WorkerHeartbeat struct {
	WorkerID   string
	Host       string
	Version    string
	LastSeenAt time.Time
	Status     string
}

type WorkerRegistration struct {
	WorkerID      string
	SessionID     string
	LeaseExpireAt time.Time
	RenewedAt     time.Time
}
