// Package sqlcgen is the sqlc-generated metadata query package. Do not edit.
// input: internal/meta/sql/*.sql and the migrations schema
// output: typed query methods for leases, task runs, and worker heartbeats
// pos: generated query layer under internal/meta; refresh with make sqlc-generate
// note: if this file changes, update this header and module README.md.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	// Epoch increases only when a different worker takes an expired lease.
	// The same worker_id keeps the epoch, including after restart once the lease
	// has expired. A released row stores an empty owner, so the next acquire
	// is a different owner and the epoch increases. A missing row inserts epoch 1.
	// Assign epoch before owner_worker_id so the comparison sees the previous owner.
	AcquireTaskLease(ctx context.Context, arg AcquireTaskLeaseParams) error
	FinishTaskRun(ctx context.Context, arg FinishTaskRunParams) error
	GetCurrentDBTime(ctx context.Context) (time.Time, error)
	GetTaskLease(ctx context.Context, taskID string) (TaskLease, error)
	ListTaskRuns(ctx context.Context, arg ListTaskRunsParams) ([]TaskRun, error)
	ListWorkerHeartbeats(ctx context.Context, limit int32) ([]WorkerHeartbeat, error)
	LoadTaskRunState(ctx context.Context, taskID string) (sql.NullString, error)
	ReleaseTaskLease(ctx context.Context, arg ReleaseTaskLeaseParams) (sql.Result, error)
	RenewTaskLease(ctx context.Context, arg RenewTaskLeaseParams) (sql.Result, error)
	UpsertTaskRun(ctx context.Context, arg UpsertTaskRunParams) error
	UpsertWorkerHeartbeat(ctx context.Context, arg UpsertWorkerHeartbeatParams) error
}

var _ Querier = (*Queries)(nil)
