// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AcquireTaskLease(ctx context.Context, arg AcquireTaskLeaseParams) error
	FinishTaskRun(ctx context.Context, arg FinishTaskRunParams) error
	GetCurrentDBTime(ctx context.Context) (time.Time, error)
	GetTaskLease(ctx context.Context, taskID string) (TaskLease, error)
	ListTaskRuns(ctx context.Context, arg ListTaskRunsParams) ([]TaskRun, error)
	ListWorkerHeartbeats(ctx context.Context, limit int32) ([]WorkerHeartbeat, error)
	LoadTaskRunState(ctx context.Context, taskID string) (sql.NullString, error)
	ReleaseTaskLease(ctx context.Context, arg ReleaseTaskLeaseParams) (sql.Result, error)
	RenewTaskLease(ctx context.Context, arg RenewTaskLeaseParams) (sql.Result, error)
	UpsertTaskRun(ctx context.Context, arg UpsertTaskRunParams) error
	UpsertWorkerHeartbeat(ctx context.Context, arg UpsertWorkerHeartbeatParams) error
}

var _ Querier = (*Queries)(nil)
