// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: task_runs_worker_heartbeats.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const finishTaskRun = `-- name: FinishTaskRun :exec
UPDATE task_runs
SET ended_at = ?, end_reason = ?
WHERE run_id = ?
  AND ended_at IS NULL
`

type FinishTaskRunParams struct {
	EndedAt   sql.NullTime
	EndReason sql.NullString
	RunID     string
}

func (q *Queries) FinishTaskRun(ctx context.Context, arg FinishTaskRunParams) error {
	_, err := q.db.ExecContext(ctx, finishTaskRun, arg.EndedAt, arg.EndReason, arg.RunID)
	return err
}

const listTaskRuns = `-- name: ListTaskRuns :many
SELECT run_id, task_id, worker_id, epoch, started_at, ended_at, end_reason
FROM task_runs
WHERE task_id = ?
ORDER BY started_at DESC
LIMIT ?
`

type ListTaskRunsParams struct {
	TaskID string
	Limit  int32
}

func (q *Queries) ListTaskRuns(ctx context.Context, arg ListTaskRunsParams) ([]TaskRun, error) {
	rows, err := q.db.QueryContext(ctx, listTaskRuns, arg.TaskID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskRun{}
	for rows.Next() {
		var i TaskRun
		if err := rows.Scan(
			&i.RunID,
			&i.TaskID,
			&i.WorkerID,
			&i.Epoch,
			&i.StartedAt,
			&i.EndedAt,
			&i.EndReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerHeartbeats = `-- name: ListWorkerHeartbeats :many
SELECT worker_id, host, version, last_seen_at, status
FROM worker_heartbeats
ORDER BY worker_id ASC
LIMIT ?
`

func (q *Queries) ListWorkerHeartbeats(ctx context.Context, limit int32) ([]WorkerHeartbeat, error) {
	rows, err := q.db.QueryContext(ctx, listWorkerHeartbeats, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkerHeartbeat{}
	for rows.Next() {
		var i WorkerHeartbeat
		if err := rows.Scan(
			&i.WorkerID,
			&i.Host,
			&i.Version,
			&i.LastSeenAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadTaskRunState = `-- name: LoadTaskRunState :one
SELECT run_id
FROM backup_tasks
WHERE id = ?
`

func (q *Queries) LoadTaskRunState(ctx context.Context, taskID string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, loadTaskRunState, taskID)
	var run_id sql.NullString
	err := row.Scan(&run_id)
	return run_id, err
}

const upsertTaskRun = `-- name: UpsertTaskRun :exec
INSERT INTO task_runs (run_id, task_id, worker_id, epoch, started_at)
VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
)
ON DUPLICATE KEY UPDATE
  task_id = VALUES(task_id),
  worker_id = VALUES(worker_id),
  epoch = VALUES(epoch),
  started_at = VALUES(started_at)
`

type UpsertTaskRunParams struct {
	RunID     string
	TaskID    string
	WorkerID  string
	Epoch     int64
	StartedAt time.Time
}

func (q *Queries) UpsertTaskRun(ctx context.Context, arg UpsertTaskRunParams) error {
	_, err := q.db.ExecContext(ctx, upsertTaskRun,
		arg.RunID,
		arg.TaskID,
		arg.WorkerID,
		arg.Epoch,
		arg.StartedAt,
	)
	return err
}

const upsertWorkerHeartbeat = `-- name: UpsertWorkerHeartbeat :exec
INSERT INTO worker_heartbeats (worker_id, host, version, last_seen_at, status)
VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
)
ON DUPLICATE KEY UPDATE
  host = VALUES(host),
  version = VALUES(version),
  last_seen_at = VALUES(last_seen_at),
  status = VALUES(status)
`

type UpsertWorkerHeartbeatParams struct {
	WorkerID   string
	Host       string
	Version    string
	LastSeenAt time.Time
	Status     string
}

func (q *Queries) UpsertWorkerHeartbeat(ctx context.Context, arg UpsertWorkerHeartbeatParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkerHeartbeat,
		arg.WorkerID,
		arg.Host,
		arg.Version,
		arg.LastSeenAt,
		arg.Status,
	)
	return err
}
