CREATE DATABASE IF NOT EXISTS binlog_meta;

CREATE DATABASE IF NOT EXISTS binlog_e2e_57;
CREATE DATABASE IF NOT EXISTS binlog_e2e_80;
CREATE DATABASE IF NOT EXISTS binlog_e2e_percona57;
CREATE DATABASE IF NOT EXISTS binlog_e2e_percona80;

CREATE USER IF NOT EXISTS 'repl'@'%' IDENTIFIED BY 'replpass';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'repl'@'%';
GRANT ALL PRIVILEGES ON binlog_e2e_57.* TO 'repl'@'%';
GRANT ALL PRIVILEGES ON binlog_e2e_80.* TO 'repl'@'%';
GRANT ALL PRIVILEGES ON binlog_e2e_percona57.* TO 'repl'@'%';
GRANT ALL PRIVILEGES ON binlog_e2e_percona80.* TO 'repl'@'%';

CREATE USER IF NOT EXISTS 'meta'@'%' IDENTIFIED BY 'metapass';
GRANT ALL PRIVILEGES ON binlog_meta.* TO 'meta'@'%';

CREATE USER IF NOT EXISTS 'repl_meta'@'%' IDENTIFIED BY 'MetaRepl!2026';
GRANT REPLICATION SLAVE ON *.* TO 'repl_meta'@'%';

CREATE USER IF NOT EXISTS 'proxysql_monitor'@'%' IDENTIFIED BY 'MetaMon!2026';
GRANT REPLICATION CLIENT, PROCESS ON *.* TO 'proxysql_monitor'@'%';

CREATE TABLE IF NOT EXISTS binlog_e2e_57.t1 (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  v VARCHAR(1024) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS binlog_e2e_80.t1 (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  v VARCHAR(1024) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS binlog_e2e_percona57.t1 (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  v VARCHAR(1024) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS binlog_e2e_percona80.t1 (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  v VARCHAR(1024) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

FLUSH PRIVILEGES;
