#!/usr/bin/env bash
# input: frontend source tree, node toolchain, and build configuration dependencies
# output: compiled frontend assets synchronized into backend static serving directory, with an L3 header stamped onto each JS bundle and an ESM syntax check; locale messages compiled before the Vite build; npm ci when vite is missing
# pos: build pipeline bridge between frontend artifacts and backend embedded UI delivery
# note: if this file changes, update this header and module README.md.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
FRONTEND_DIR="$ROOT_DIR/frontend"
UI_STATIC_DIR="$ROOT_DIR/internal/ui/static"

echo "[ui] build frontend (base=/ui/)"
(
  cd "$FRONTEND_DIR"
  if [[ ! -x node_modules/.bin/vite ]]; then
    echo "[ui] vite not found; running npm ci"
    npm ci
  fi
  npm run test:locales
  npm run build
)

echo "[ui] sync dist -> internal/ui/static"
mkdir -p "$UI_STATIC_DIR"
snap="$(mktemp -d)"
cp -a "$UI_STATIC_DIR/." "$snap/"
cp -R "$FRONTEND_DIR/dist/." "$UI_STATIC_DIR/"

# Stamp the L3 header with a byte copy. Do not interpolate the bundle:
# the shipped entry was Vite output plus one hand-inserted "}" after "$t".
# Leave a chunk alone when its JS body already matches, so a rebuild does not
# rewrite historical headers.
UI_DIST="$FRONTEND_DIR/dist" UI_STATIC="$UI_STATIC_DIR" UI_SNAP="$snap" node <<'JS'
const fs = require("fs");
const path = require("path");
const dist = process.env.UI_DIST;
const staticDir = process.env.UI_STATIC;
const snap = process.env.UI_SNAP;
const header = Buffer.from(
  [
    "// input: Vite-generated frontend modules and dependency chunks",
    "// output: browser-executable embedded UI bundle",
    "// pos: generated static asset served under /ui/assets",
    "// note: generated by make ui-build; update internal/ui/static/assets/README.md if the layout changes.",
    "",
    "",
  ].join("\n")
);
function stripHeader(buf) {
  let s = buf.toString("utf8");
  if (!s.startsWith("// input:")) return buf;
  while (s.startsWith("//") || s.startsWith("\n")) {
    if (s.startsWith("//")) {
      const nl = s.indexOf("\n");
      if (nl < 0) return Buffer.alloc(0);
      s = s.slice(nl + 1);
    } else {
      s = s.slice(1);
    }
  }
  return Buffer.from(s);
}
function walk(dir) {
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, ent.name);
    if (ent.isDirectory()) {
      walk(p);
      continue;
    }
    if (!ent.name.endsWith(".js")) continue;
    const rel = path.relative(dist, p);
    const dest = path.join(staticDir, rel);
    const fresh = fs.readFileSync(dest);
    const prevPath = path.join(snap, rel);
    if (fs.existsSync(prevPath)) {
      const prev = fs.readFileSync(prevPath);
      if (stripHeader(prev).equals(fresh)) {
        fs.writeFileSync(dest, prev);
        continue;
      }
    }
    fs.writeFileSync(dest, Buffer.concat([header, fresh]));
  }
}
walk(dist);
JS
rm -rf "$snap"

"$ROOT_DIR/scripts/check-ui-bundle.sh"

echo "[ui] done: backend /ui/ now serves latest frontend build"
