// Package swaggerdocs Code generated by swaggo/swag. DO NOT EDIT
// input: Swagger annotations and API contract types from internal/api
// output: embedded OpenAPI metadata including cluster overview single_process, workers 500, the task batch endpoint, PUT /api/tasks/{id} plain-text 400 when a live dump's source, start, storage, or cluster_key would change, POST /api/tasks/{id}/adopt, GET /api/tasks/{id}/checkpoint resume file/pos where epoch greater than 1 follows a readable file_path and does not rewind an unreadable tail to position 4, GET /api/tasks/{id}/replay with optional UTC stop_datetime, GET /api/tasks/{id}/replay/archive, GET /api/tasks/{id}/files/{name} from local disk or a sealed uploaded object, and BinlogFile.checksum, with start_pos and end_pos nullable so an unknown position is JSON null
// pos: generated API documentation consumed by the Swagger handler
// note: if this file changes, update this header and internal/swaggerdocs/README.md.
package swaggerdocs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/cluster/overview": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cluster"
                ],
                "summary": "Get cluster overview",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.clusterOverview"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/dashboard": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get task dashboard with replication delay overview",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by source host; localhost and explicit loopback literals share one identity, other hosts match exact spelling",
                        "name": "host",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by source port",
                        "name": "port",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by task state",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 100, range 1-500; values above 500 return 400)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Zero-based page offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.dashboardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Service health check (JSON)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/sources/lookup": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Lookup tasks by source host and port",
                "parameters": [
                    {
                        "type": "string",
                        "description": "MySQL source host (required); localhost and explicit loopback literals (127/8, ::1, including bracketed IPv6) share one identity, other hosts match exact spelling",
                        "name": "host",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "MySQL source port (required, 1-65535)",
                        "name": "port",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.sourceLookupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/summary": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get task summary counters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by source host; localhost and explicit loopback literals share one identity, other hosts match exact spelling",
                        "name": "host",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by source port",
                        "name": "port",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.summaryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "List tasks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by source host; localhost and explicit loopback literals share one identity, other hosts match exact spelling",
                        "name": "host",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by source port",
                        "name": "port",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by task state (CREATED, STARTING, RUNNING, LEASE_DEGRADED, REBUILDING_FILE, RETRY_BACKOFF, FAILED, STOPPING, STOPPED)",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 100, range 1-500; values above 500 return 400 invalid limit)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Zero-based page offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.taskListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Create or list tasks",
                "parameters": [
                    {
                        "description": "Task create payload (name:1-255, cluster_key:[a-zA-Z0-9._-], source/start/storage 按字段规则校验)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/tasks.Task"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.apiErrorBody"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/batch": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Create tasks in batch",
                "parameters": [
                    {
                        "description": "Batch task create payload (1-100 items)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.batchCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.batchCreateResult"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.apiErrorBody"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Get task by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tasks.Task"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "While the task is RUNNING, STARTING, LEASE_DEGRADED, or RETRY_BACKOFF, changing source, start, storage, or cluster_key returns plain-text 400 stop the task before changing source, start, storage, or cluster_key. A name-only change is accepted. Stop the task, update, then start.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Update task configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Task update payload（cluster_key 必填，仅允许 [a-zA-Z0-9._-]，禁止 / \\\\ ..；name/source/start/storage 按字段规则校验）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.updateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tasks.Task"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Tasks"
                ],
                "summary": "Delete task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/adopt": {
            "post": {
                "description": "Attaches cluster_key and source to a standalone disk-discovered task id. Omitted start resumes at FILE_POS at the size of the highest local segment. Does not start replication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Adopt a leftover on-disk task directory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "cluster_key and source (host/port/user/password/flavor) are required. name, start, and storage are optional.",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.updateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tasks.Task"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/checkpoint": {
            "get": {
                "description": "Returns the file, pos, and gtid_set the next Start continues from. A local open segment with a complete event wins over the stored checkpoint. gtid_set is included when that stored checkpoint has the same file and pos. With no local event, the stored checkpoint is returned. Epoch greater than 1 rewinds pos to 4 only when the catalog has no row for that tail. A readable binlog_files.file_path continues from the last complete event in that directory. A checkpoint inside a sealed UPLOADED object is not rewound. An unreadable open segment returns the stored checkpoint; Start then fails with SEGMENT_NOT_ON_WORKER and does not open a new directory. 404 when neither exists.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Get task checkpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/binlog.Checkpoint"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/events": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "List task events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Event list limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tasks.TaskEvent"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/files": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "List binlog file metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "File list limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tasks.BinlogFile"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/files/retry-upload": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Retry failed upload binlog files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "maximum": 1000,
                        "minimum": 1,
                        "type": "integer",
                        "default": 100,
                        "description": "Retry upload limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tasks.UploadRetryStats"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/files/{name}": {
            "get": {
                "description": "Streams one basename already listed by GET /api/tasks/{id}/files. Content-Type is application/octet-stream and Content-Disposition filename is that basename. A file at {data_dir}/{id}/{name} is served at its size at open, including *.open.e* while the task is RUNNING or STOPPED. When that file is missing, a sealed row with upload_state UPLOADED and a non-empty object_key is read from the configured object store, and the body length is the object size at open. LOCAL_ONLY, UPLOAD_FAILED, an empty object_key, an open segment with no local file, or object upload not configured is 404 segment not found on this process. Catalog file_path is not a byte source. A slash, backslash, or .. is 400. A missing task is 404.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Download one inventory binlog segment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "On-disk basename",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "raw binlog bytes",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "invalid segment name",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "task not found or segment not on this process",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/lease": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cluster"
                ],
                "summary": "Get task lease info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.taskLeaseView"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/replay": {
            "get": {
                "description": "One file_path per source index, ascending. When a sealed name and .open.e* share an index, the path is the highest-epoch open segment. locations is the same order: local, bucket, or both. bucket means that path is the catalog file_path and is not on this process; download and replay/archive still read the object. Do not pass a bucket path to mysqlbinlog until the file is downloaded. Without stop_datetime, limit is the same inventory window as GET /files and the body omits command. stop_datetime (UTC) selects the point-in-time window instead of limit: paths cover events at or after optional start_datetime and before stop_datetime, and command is the TZ=UTC client invocation. An empty cover is 200 with empty paths and command. Invalid datetimes are 400.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "List the mysqlbinlog replay set for a task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Inventory window limit (same as files). Ignored when stop_datetime is set.",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "UTC stop time, YYYY-MM-DD HH:MM:SS or RFC3339. Required for the point-in-time window.",
                        "name": "stop_datetime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Optional UTC start time. Requires stop_datetime.",
                        "name": "start_datetime",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tasks.PITRSet"
                        }
                    },
                    "400": {
                        "description": "invalid stop_datetime, invalid start_datetime, stop_datetime is required, or start_datetime is after stop_datetime",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/replay/archive": {
            "get": {
                "description": "USTAR archive whose members are the basenames from GET /api/tasks/{id}/replay for the same limit, one per source index. stop_datetime uses that route's point-in-time window instead of limit. A sealed name and .open.e* still keep the highest-epoch open segment. Each member uses the GET /api/tasks/{id}/files/{name} open rules: a local file wins, including *.open.e* while RUNNING or STOPPED; a missing local file is read only for a sealed UPLOADED row with a non-empty object_key. An empty selection is 200 and an empty tar. If any selected segment cannot be opened, the response is an error and the body is not a tar. A missing task is 404 task not found.",
                "produces": [
                    "application/x-tar"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Download the mysqlbinlog replay set as one tar",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Inventory window limit (same as replay). Ignored when stop_datetime is set.",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "UTC stop time. Same window as GET /api/tasks/{id}/replay.",
                        "name": "stop_datetime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Optional UTC start time. Requires stop_datetime.",
                        "name": "start_datetime",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ustar archive task-{id}-replay.tar",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "invalid segment name or invalid datetime",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "task not found or segment not found on this process",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/replication": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Get task replication delay and latest position",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.taskReplicationResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/runs": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cluster"
                ],
                "summary": "List task run sessions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Run history limit (default 10, max 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.taskRunView"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/start": {
            "post": {
                "tags": [
                    "Tasks"
                ],
                "summary": "Start task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/stop": {
            "post": {
                "tags": [
                    "Tasks"
                ],
                "summary": "Stop task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tasks/{id}/upload-failures/reasons": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Aggregate upload failure reasons",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "maximum": 200,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Failure reason list limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tasks.UploadFailureReason"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/workers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cluster"
                ],
                "summary": "List cluster workers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Workers list limit (max 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.workerItem"
                            }
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "tags": [
                    "System"
                ],
                "summary": "Service health check",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.apiErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "api.batchCreateRequest": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.createTaskRequest"
                    }
                }
            }
        },
        "api.batchCreateResult": {
            "type": "object",
            "properties": {
                "cluster_key": {
                    "type": "string"
                },
                "error": {
                    "$ref": "#/definitions/api.apiErrorBody"
                },
                "index": {
                    "type": "integer"
                },
                "task": {
                    "$ref": "#/definitions/tasks.Task"
                }
            }
        },
        "api.clusterOverview": {
            "type": "object",
            "properties": {
                "leased_task_count": {
                    "type": "integer"
                },
                "running_task_count": {
                    "type": "integer"
                },
                "single_process": {
                    "type": "boolean"
                },
                "task_count": {
                    "type": "integer"
                },
                "worker_count": {
                    "type": "integer"
                },
                "workers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.workerItem"
                    }
                }
            }
        },
        "api.createTaskRequest": {
            "type": "object",
            "properties": {
                "cluster_key": {
                    "description": "ClusterKey 集群标识（必填；仅允许 [a-zA-Z0-9._-]；禁止 / \\ ..）。",
                    "type": "string"
                },
                "name": {
                    "description": "Name 任务名（trim 后 1-255 字符）。",
                    "type": "string"
                },
                "source": {
                    "description": "Source 源库配置：host/user 必填且不得含空白；port 1-65535；flavor 为空默认 mysql。",
                    "allOf": [
                        {
                            "$ref": "#/definitions/tasks.SourceConfig"
                        }
                    ]
                },
                "start": {
                    "description": "Start 起点策略：LATEST|FILE_POS|GTID。",
                    "allOf": [
                        {
                            "$ref": "#/definitions/tasks.StartConfig"
                        }
                    ]
                },
                "storage": {
                    "description": "Storage 存储策略：retention_days 必须在 1..3650。local_retention_days 与 bucket_retention_days 省略或 0 时等于 retention_days。桶保留短于本地保留则 400。",
                    "allOf": [
                        {
                            "$ref": "#/definitions/tasks.Storage"
                        }
                    ]
                }
            }
        },
        "api.dashboardResponse": {
            "type": "object",
            "properties": {
                "generated_at": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.sourceOverview"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/api.summaryResponse"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.dashboardTaskItem"
                    }
                },
                "threshold_seconds": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.dashboardTaskItem": {
            "type": "object",
            "properties": {
                "replication": {
                    "$ref": "#/definitions/api.taskReplicationResponse"
                },
                "task": {
                    "$ref": "#/definitions/tasks.Task"
                }
            }
        },
        "api.sourceLookupResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "exists": {
                    "type": "boolean"
                },
                "host": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "task_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.sourceOverview": {
            "type": "object",
            "properties": {
                "abnormal": {
                    "type": "integer"
                },
                "delayed": {
                    "type": "integer"
                },
                "host": {
                    "type": "string"
                },
                "normal": {
                    "type": "integer"
                },
                "port": {
                    "type": "integer"
                },
                "running": {
                    "type": "integer"
                },
                "starting": {
                    "type": "integer"
                },
                "task_count": {
                    "type": "integer"
                }
            }
        },
        "api.summaryResponse": {
            "type": "object",
            "properties": {
                "abnormal": {
                    "type": "integer"
                },
                "delayed": {
                    "type": "integer"
                },
                "failed": {
                    "type": "integer"
                },
                "normal": {
                    "type": "integer"
                },
                "retry_backoff": {
                    "type": "integer"
                },
                "running": {
                    "type": "integer"
                },
                "starting": {
                    "type": "integer"
                },
                "stopped": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.taskLeaseView": {
            "type": "object",
            "properties": {
                "epoch": {
                    "type": "integer"
                },
                "owner_worker_id": {
                    "type": "string"
                },
                "state": {
                    "$ref": "#/definitions/tasks.State"
                },
                "task_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.taskListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tasks.Task"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.taskReplicationResponse": {
            "type": "object",
            "properties": {
                "delay_seconds": {
                    "description": "DelaySeconds is a sampled lag. Nil means there is no event-time sample, so JSON omits the field.\nA non-nil 0 is caught up. omitempty on a plain int64 would drop that zero and the Console would show \"--\".",
                    "type": "integer"
                },
                "has_progress": {
                    "type": "boolean"
                },
                "last_error": {
                    "type": "string"
                },
                "last_event_at": {
                    "type": "string"
                },
                "last_event_file": {
                    "type": "string"
                },
                "last_event_pos": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                },
                "state": {
                    "$ref": "#/definitions/tasks.State"
                },
                "status": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "threshold_seconds": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.taskRunView": {
            "type": "object",
            "properties": {
                "end_reason": {
                    "type": "string"
                },
                "ended_at": {
                    "type": "string"
                },
                "epoch": {
                    "type": "integer"
                },
                "run_id": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "worker_id": {
                    "type": "string"
                }
            }
        },
        "api.updateTaskRequest": {
            "type": "object",
            "properties": {
                "cluster_key": {
                    "description": "ClusterKey 集群标识（必填；仅允许 [a-zA-Z0-9._-]；禁止 / \\ ..）。",
                    "type": "string"
                },
                "name": {
                    "description": "Name 任务名（trim 后 1-255 字符）。",
                    "type": "string"
                },
                "source": {
                    "description": "Source 源库配置：host/user 必填且不得含空白；port 1-65535；flavor 为空默认 mysql。",
                    "allOf": [
                        {
                            "$ref": "#/definitions/tasks.SourceConfig"
                        }
                    ]
                },
                "start": {
                    "description": "Start 起点策略：LATEST|FILE_POS|GTID。",
                    "allOf": [
                        {
                            "$ref": "#/definitions/tasks.StartConfig"
                        }
                    ]
                },
                "storage": {
                    "description": "Storage 存储策略：retention_days 必须在 1..3650。local_retention_days 与 bucket_retention_days 省略或 0 时等于 retention_days。桶保留短于本地保留则 400。",
                    "allOf": [
                        {
                            "$ref": "#/definitions/tasks.Storage"
                        }
                    ]
                }
            }
        },
        "api.workerItem": {
            "type": "object",
            "properties": {
                "has_updated": {
                    "type": "boolean"
                },
                "host": {
                    "type": "string"
                },
                "last_seen_at": {
                    "type": "string"
                },
                "leased": {
                    "type": "integer"
                },
                "online": {
                    "type": "boolean"
                },
                "running": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "task_count": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                },
                "worker_id": {
                    "type": "string"
                }
            }
        },
        "binlog.Checkpoint": {
            "type": "object",
            "properties": {
                "file": {
                    "type": "string"
                },
                "gtid_set": {
                    "type": "string"
                },
                "pos": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "tasks.BinlogFile": {
            "type": "object",
            "properties": {
                "checksum": {
                    "description": "Checksum is match when the stored object is the same bytes as the sealed file.\nmismatch means that comparison finished and the bytes differ.\nEmpty means the object HEAD did not finish. Empty is not verified.\nOnly match is stored on an UPLOADED row. A mismatch or an unfinished check is UPLOAD_FAILED.",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "end_pos": {
                    "description": "Last complete event end log position. JSON null means the end is not known. The value 0 is not stored.",
                    "type": "integer",
                    "x-nullable": true
                },
                "file_name": {
                    "type": "string"
                },
                "file_path": {
                    "type": "string"
                },
                "location": {
                    "description": "local, bucket, or both. Computed on the files list and not stored. bucket means the sealed UPLOADED object is the only copy and file_path is not on this process.",
                    "type": "string"
                },
                "object_key": {
                    "type": "string"
                },
                "sealed_at": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "start_pos": {
                    "description": "First event position in the segment. JSON null means the start is not known. The value 0 is not stored.",
                    "type": "integer",
                    "x-nullable": true
                },
                "state": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "upload_error": {
                    "type": "string"
                },
                "upload_state": {
                    "type": "string"
                },
                "uploaded_at": {
                    "type": "string"
                }
            }
        },
        "tasks.PITRSet": {
            "type": "object",
            "properties": {
                "client": {
                    "type": "string"
                },
                "client_hint": {
                    "type": "string"
                },
                "command": {
                    "type": "string"
                },
                "flavor": {
                    "type": "string"
                },
                "locations": {
                    "description": "Same order as paths. bucket means that path is not on this process.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "paths": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "tasks.SourceConfig": {
            "type": "object",
            "properties": {
                "flavor": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "password": {
                    "description": "仅用于输入，API 响应前会清空",
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "semi_sync": {
                    "description": "SemiSync=true 时尝试以 semi-sync 协议拉流；主库不支持时会自动降级为异步。",
                    "type": "boolean"
                },
                "server_id": {
                    "type": "integer"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "tasks.StartConfig": {
            "type": "object",
            "properties": {
                "file": {
                    "type": "string"
                },
                "gtid_set": {
                    "type": "string"
                },
                "mode": {
                    "$ref": "#/definitions/tasks.StartMode"
                },
                "pos": {
                    "type": "integer"
                }
            }
        },
        "tasks.StartMode": {
            "type": "string",
            "enum": [
                "LATEST",
                "FILE_POS",
                "GTID"
            ],
            "x-enum-varnames": [
                "StartModeLatest",
                "StartModeFilePos",
                "StartModeGTID"
            ]
        },
        "tasks.State": {
            "type": "string",
            "enum": [
                "CREATED",
                "STARTING",
                "RUNNING",
                "LEASE_DEGRADED",
                "REBUILDING_FILE",
                "RETRY_BACKOFF",
                "FAILED",
                "STOPPING",
                "STOPPED"
            ],
            "x-enum-varnames": [
                "StateCreated",
                "StateStarting",
                "StateRunning",
                "StateLeaseDegraded",
                "StateRebuildingFile",
                "StateRetryBackoff",
                "StateFailed",
                "StateStopping",
                "StateStopped"
            ]
        },
        "tasks.Storage": {
            "type": "object",
            "properties": {
                "bucket_retention_days": {
                    "type": "integer"
                },
                "dir": {
                    "type": "string"
                },
                "local_retention_days": {
                    "type": "integer"
                },
                "retention_days": {
                    "type": "integer"
                }
            }
        },
        "tasks.Task": {
            "type": "object",
            "properties": {
                "cluster_key": {
                    "type": "string"
                },
                "epoch": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "last_error": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_worker_id": {
                    "type": "string"
                },
                "run_id": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/tasks.SourceConfig"
                },
                "start": {
                    "$ref": "#/definitions/tasks.StartConfig"
                },
                "state": {
                    "$ref": "#/definitions/tasks.State"
                },
                "storage": {
                    "$ref": "#/definitions/tasks.Storage"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "tasks.TaskEvent": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "sequence": {
                    "type": "integer"
                },
                "task_id": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "tasks.UploadFailureReason": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "latest_time": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "tasks.UploadRetryStats": {
            "type": "object",
            "properties": {
                "failed": {
                    "type": "integer"
                },
                "scanned": {
                    "type": "integer"
                },
                "skipped": {
                    "type": "integer"
                },
                "succeeded": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Binlog Server API",
	Description:      "Centralized MySQL binlog backup service API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
